# Generated by Django 5.1.1 on 2024-09-12 08:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadHandler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.TextField(editable=False)),
                ('file_size', models.BigIntegerField(editable=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
